name: monitor_dbonly
services: 
  db:
    image: postgres:15.4-alpine
    container_name: monitor_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=monitor
      - POSTGRES_USER=postgres
      - PGUSER=postgres
    healthcheck:
      test: [ "CMD-SHELL" , "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
