#
# Sample configuration file
#
# TODO: Copy this file to `config.toml`, then change these values to match
# your conficguration.
#
# Note that `config.toml` is not included in source control.
#

[EventHub]
ConnectionString = "--fill me in--"
HubName = "ehub"
